apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: The cluster-version operator manages OpenShift updates and reconciles core resources and cluster operators.
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
  name: metrics-client-ca
  namespace: openshift-cluster-version
data: {}
